import { BoneAngles, GestureType } from './types';

export const GESTURE_PRESETS: Record<GestureType, BoneAngles> = {
  idle: {
    headTilt: 0,
    headRotate: 0,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -15,
    rightForearm: -10,
    leftHandPose: 'flat',
    rightHandPose: 'flat',
  },
  wave: {
    headTilt: -5,
    headRotate: 2,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -125,
    rightForearm: -45,
    leftHandPose: 'flat',
    rightHandPose: 'wave',
  },
  pointLeft: {
    headTilt: 4,
    headRotate: -12,
    leftUpperArm: 75,
    leftForearm: 20,
    rightUpperArm: -15,
    rightForearm: -10,
    leftHandPose: 'pointing',
    rightHandPose: 'flat',
  },
  pointRight: {
    headTilt: -4,
    headRotate: 12,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -75,
    rightForearm: -20,
    leftHandPose: 'flat',
    rightHandPose: 'pointing',
  },
  pointUp: {
    headTilt: -8,
    headRotate: 0,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -110,
    rightForearm: -15,
    leftHandPose: 'flat',
    rightHandPose: 'pointing',
  },
  pointDown: {
    headTilt: 6,
    headRotate: 0,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -40,
    rightForearm: -45,
    leftHandPose: 'flat',
    rightHandPose: 'pointing',
  },
  pointAtTarget: {
    headTilt: 0,
    headRotate: 0,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -65,
    rightForearm: -25,
    leftHandPose: 'flat',
    rightHandPose: 'pointing',
  },
  present: {
    headTilt: -3,
    headRotate: 8,
    leftUpperArm: 20,
    leftForearm: 15,
    rightUpperArm: -60,
    rightForearm: -40,
    leftHandPose: 'flat',
    rightHandPose: 'flat',
  },
  explainOneHand: {
    headTilt: 2,
    headRotate: -4,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -45,
    rightForearm: -55,
    leftHandPose: 'flat',
    rightHandPose: 'flat',
  },
  explainBothHands: {
    headTilt: 0,
    headRotate: 0,
    leftUpperArm: 45,
    leftForearm: 45,
    rightUpperArm: -45,
    rightForearm: -45,
    leftHandPose: 'flat',
    rightHandPose: 'flat',
  },
  thinking: {
    headTilt: 10,
    headRotate: -6,
    leftUpperArm: 20,
    leftForearm: 15,
    rightUpperArm: -75,
    rightForearm: -110,
    leftHandPose: 'flat',
    rightHandPose: 'chin',
  },
  handOnChin: {
    headTilt: 8,
    headRotate: -8,
    leftUpperArm: 20,
    leftForearm: 15,
    rightUpperArm: -80,
    rightForearm: -115,
    leftHandPose: 'flat',
    rightHandPose: 'chin',
  },
  thumbsUp: {
    headTilt: -4,
    headRotate: 4,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -55,
    rightForearm: -65,
    leftHandPose: 'flat',
    rightHandPose: 'thumbsUp',
  },
  celebrate: {
    headTilt: -8,
    headRotate: 0,
    leftUpperArm: 130,
    leftForearm: 30,
    rightUpperArm: -130,
    rightForearm: -30,
    leftHandPose: 'wave',
    rightHandPose: 'wave',
  },
  encourage: {
    headTilt: -3,
    headRotate: 2,
    leftUpperArm: 30,
    leftForearm: 25,
    rightUpperArm: -30,
    rightForearm: -25,
    leftHandPose: 'flat',
    rightHandPose: 'thumbsUp',
  },
  shrug: {
    headTilt: 6,
    headRotate: 0,
    leftUpperArm: 50,
    leftForearm: 60,
    rightUpperArm: -50,
    rightForearm: -60,
    leftHandPose: 'flat',
    rightHandPose: 'flat',
  },
  stop: {
    headTilt: 0,
    headRotate: 0,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -85,
    rightForearm: -10,
    leftHandPose: 'flat',
    rightHandPose: 'flat',
  },
  wait: {
    headTilt: 2,
    headRotate: 0,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -35,
    rightForearm: -40,
    leftHandPose: 'flat',
    rightHandPose: 'flat',
  },
  comeHere: {
    headTilt: -2,
    headRotate: 4,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -50,
    rightForearm: -70,
    leftHandPose: 'flat',
    rightHandPose: 'wave',
  },
  handsOpen: {
    headTilt: 0,
    headRotate: 0,
    leftUpperArm: 35,
    leftForearm: 35,
    rightUpperArm: -35,
    rightForearm: -35,
    leftHandPose: 'flat',
    rightHandPose: 'flat',
  },
  noPeek: {
    headTilt: 4,
    headRotate: -5,
    leftUpperArm: 20,
    leftForearm: 15,
    rightUpperArm: -85,
    rightForearm: -20,
    leftHandPose: 'flat',
    rightHandPose: 'noPeek',
  },
  doubleThumbsUp: {
    headTilt: -5,
    headRotate: 0,
    leftUpperArm: 55,
    leftForearm: 65,
    rightUpperArm: -55,
    rightForearm: -65,
    leftHandPose: 'thumbsUp',
    rightHandPose: 'thumbsUp',
  },
  readingBook: {
    headTilt: 8,
    headRotate: -4,
    leftUpperArm: 40,
    leftForearm: 75,
    rightUpperArm: -35,
    rightForearm: -65,
    leftHandPose: 'book',
    rightHandPose: 'pointing',
  },
  crossArms: {
    headTilt: 2,
    headRotate: 0,
    leftUpperArm: 50,
    leftForearm: 95,
    rightUpperArm: -50,
    rightForearm: -95,
    leftHandPose: 'fist',
    rightHandPose: 'fist',
  },
  writeOnBoard: {
    headTilt: -4,
    headRotate: 8,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -95,
    rightForearm: -35,
    leftHandPose: 'flat',
    rightHandPose: 'pointing',
  },
  heartHands: {
    headTilt: -3,
    headRotate: 0,
    leftUpperArm: 45,
    leftForearm: 85,
    rightUpperArm: -45,
    rightForearm: -85,
    leftHandPose: 'heart',
    rightHandPose: 'heart',
  },
  bow: {
    headTilt: 18,
    headRotate: 0,
    leftUpperArm: 20,
    leftForearm: 20,
    rightUpperArm: -20,
    rightForearm: -20,
    leftHandPose: 'flat',
    rightHandPose: 'flat',
  },
  applause: {
    headTilt: -4,
    headRotate: 0,
    leftUpperArm: 40,
    leftForearm: 80,
    rightUpperArm: -40,
    rightForearm: -80,
    leftHandPose: 'clap',
    rightHandPose: 'clap',
  },
  victory: {
    headTilt: -6,
    headRotate: 4,
    leftUpperArm: 20,
    leftForearm: 15,
    rightUpperArm: -120,
    rightForearm: -25,
    leftHandPose: 'flat',
    rightHandPose: 'peace',
  },
  salute: {
    headTilt: -3,
    headRotate: 2,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -105,
    rightForearm: -120,
    leftHandPose: 'flat',
    rightHandPose: 'salute',
  },
  secretTip: {
    headTilt: 6,
    headRotate: 12,
    leftUpperArm: 20,
    leftForearm: 15,
    rightUpperArm: -85,
    rightForearm: -115,
    leftHandPose: 'flat',
    rightHandPose: 'cupped',
  },
  stretch: {
    headTilt: -10,
    headRotate: 0,
    leftUpperArm: 145,
    leftForearm: 15,
    rightUpperArm: -145,
    rightForearm: -15,
    leftHandPose: 'wave',
    rightHandPose: 'wave',
  },
  listeningEar: {
    headTilt: 8,
    headRotate: 14,
    leftUpperArm: 20,
    leftForearm: 15,
    rightUpperArm: -80,
    rightForearm: -115,
    leftHandPose: 'flat',
    rightHandPose: 'cupped',
  },
  eureka: {
    headTilt: -10,
    headRotate: 0,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -135,
    rightForearm: -10,
    leftHandPose: 'flat',
    rightHandPose: 'pointing',
  },
  facepalm: {
    headTilt: 12,
    headRotate: 0,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -85,
    rightForearm: -120,
    leftHandPose: 'flat',
    rightHandPose: 'facepalm',
  },
  flex: {
    headTilt: -5,
    headRotate: -6,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -75,
    rightForearm: -110,
    leftHandPose: 'flat',
    rightHandPose: 'fist',
  },
  shushing: {
    headTilt: 2,
    headRotate: 0,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -75,
    rightForearm: -115,
    leftHandPose: 'flat',
    rightHandPose: 'pointing',
  },
  adjustGlasses: {
    headTilt: 4,
    headRotate: 0,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -80,
    rightForearm: -115,
    leftHandPose: 'flat',
    rightHandPose: 'adjustGlasses',
  },
  highFive: {
    headTilt: -6,
    headRotate: 4,
    leftUpperArm: 15,
    leftForearm: 10,
    rightUpperArm: -115,
    rightForearm: -25,
    leftHandPose: 'flat',
    rightHandPose: 'highFive',
  },
  fingerGuns: {
    headTilt: -4,
    headRotate: 0,
    leftUpperArm: 65,
    leftForearm: 45,
    rightUpperArm: -65,
    rightForearm: -45,
    leftHandPose: 'fingerGun',
    rightHandPose: 'fingerGun',
  },
  handsOnHips: {
    headTilt: -2,
    headRotate: 0,
    leftUpperArm: 40,
    leftForearm: 90,
    rightUpperArm: -40,
    rightForearm: -90,
    leftHandPose: 'fist',
    rightHandPose: 'fist',
  },
  heartOverhead: {
    headTilt: -8,
    headRotate: 0,
    leftUpperArm: 135,
    leftForearm: 75,
    rightUpperArm: -135,
    rightForearm: -75,
    leftHandPose: 'heart',
    rightHandPose: 'heart',
  },
  cheeringRally: {
    headTilt: -10,
    headRotate: 0,
    leftUpperArm: 140,
    leftForearm: 35,
    rightUpperArm: -140,
    rightForearm: -35,
    leftHandPose: 'wave',
    rightHandPose: 'wave',
  },
};
